name: Continuous Deployment

on:
  push:
    branches: ["main"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}
    
    - name: Set up docker build
      uses: docker/setup-buildx-action@v2

    - name: Build and push docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: crazywebdev/todo-app-argocd:${{ github.sha }}

    - name: Clone repo, update docker image, update tags
      env:
        PAT: ${{ secrets.PAT}}
      run: |
        git clone https://github.com/AryanBhatDev/argo-deployment.git
        cd argo-deployment
      
        sed -i 's|image: crazywebdev/todo-app-argocd:.*|image: crazywebdev/todo-app-argocd: ${{ github.sha }}|' manifest.yml
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update deployment server image tags to ${{ github.sha }}"
        git push https://${PAT}@github.com/AryanBhatDev/argo-deployment.git master


